version: '3.8'

services:
 sql_server:
  image: mcr.microsoft.com/mssql/server:latest
  restart: always
  environment:
   - ACCEPT_EULA=Y
   - SA_PASSWORD=<Mylovefromthesky8553!>
   - attach_dbs=[{"dbName":"Anna_shop","dbFiles":["C:\\Year4\\Anny\\b\\database\\Anna_shop.MDF","C:\\Year4\\Anny\\b\\database\\Anna_shop_log.LDF"]}]
  ports:
   - '1433:1433'
  volumes:
    - C:\\Year4\\Anny\\b\\database\\:/var/opt/mssql/data